# Generated by Django 3.1.1 on 2020-09-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200918_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sellMRP',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
