# Generated by Django 3.1.1 on 2020-09-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=15)),
                ('categoryDescription', models.CharField(max_length=50)),
                ('categoryDiscount', models.IntegerField(default=0)),
                ('categoryImageUrl', models.ImageField(upload_to='category')),
            ],
        ),
    ]
