# Generated by Django 3.1.1 on 2020-09-19 20:36

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=15)),
                ('categoryDescription', models.CharField(max_length=50)),
                ('categoryDiscount', models.IntegerField(default=0)),
                ('image', cloudinary.models.CloudinaryField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1200px-Image_created_with_a_mobile_phone.png', max_length=255, verbose_name='image')),
            ],
        ),
    ]
