# Generated by Django 3.1.1 on 2020-09-19 21:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20200920_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='categoryImageurl',
        ),
        migrations.AddField(
            model_name='category',
            name='categoryImageUrl',
            field=cloudinary.models.CloudinaryField(default='com.com', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
